[package]
name = "simple-thesis"
version = "0.4.0"
entrypoint = "lib.typ"
authors = ["OrangeX4", "Jebbs"]
license = "MIT"
description = "适用于日常交流的简易论文模板。Simple Thesis for daily usage."
repository = "https://github.com/qjebbs/simple-thesis"
keywords = ["daily usage", "thesis"]
categories = ["thesis"]
exclude = ["imgs"]
compiler = "0.13.0"

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"